package com.app.sjkh.pojo.local;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@Table(name = "T_ACCEPTED_CERT_INFO")
public class AcceptedCertInfo {

    public static final String State_0 = "0";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.ID
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.CUSTNAME
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDTYPE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String idtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDNO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String idno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.ETHNIC
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String ethnic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.MOBILENO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String mobileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.CERTUID
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String certuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.BRANCHNO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String branchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.POSTID
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String postid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.ADDR
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.STATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.CREATEDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.USERSEX
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.BORTHDAY
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String borthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.NATIONALITY
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDBEGINDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String idbegindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDENDDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String idenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBILENO1
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String bkmobileno1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.UPDATEDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.POLICEORG
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String policeorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.NATIVE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    @Column(name = "native")
    private String natives;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.RISKEXP
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String riskexp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.ACCESS_CHANNEL
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private Integer accessChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.IPADDR
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String ipaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.MACADDR
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String macaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_SOURCE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String extendSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_COMPANY
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String extendCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.BANKTYPE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String banktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.BANKCODE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.INFOCOLECT_CHANNEL
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String infocolectChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.EDU
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String edu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.PROFESSION_CODE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String professionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.OPACCTKIND_FLAG
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String opacctkindFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBLIENO1
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String bkmoblieno1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.RECOMMENDNO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private String recommendno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_CERT_INFO.COMMISSION
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    private Double commission;

    @Transient
    private String certUploadState;

    public String getCertUploadState() {
        return certUploadState;
    }

    public void setCertUploadState(String certUploadState) {
        this.certUploadState = certUploadState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.ID
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.ID
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.ID
     *
     * @param id the value for OSOADATA.T_ACCEPTED_CERT_INFO.ID
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.CUSTNAME
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.CUSTNAME
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.CUSTNAME
     *
     * @param custname the value for OSOADATA.T_ACCEPTED_CERT_INFO.CUSTNAME
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDTYPE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.IDTYPE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDTYPE
     *
     * @param idtype the value for OSOADATA.T_ACCEPTED_CERT_INFO.IDTYPE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setIdtype(String idtype) {
        this.idtype = idtype == null ? null : idtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDNO
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.IDNO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDNO
     *
     * @param idno the value for OSOADATA.T_ACCEPTED_CERT_INFO.IDNO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setIdno(String idno) {
        this.idno = idno == null ? null : idno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.ETHNIC
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.ETHNIC
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getEthnic() {
        return ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.ETHNIC
     *
     * @param ethnic the value for OSOADATA.T_ACCEPTED_CERT_INFO.ETHNIC
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setEthnic(String ethnic) {
        this.ethnic = ethnic == null ? null : ethnic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.MOBILENO
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.MOBILENO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getMobileno() {
        return mobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.MOBILENO
     *
     * @param mobileno the value for OSOADATA.T_ACCEPTED_CERT_INFO.MOBILENO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno == null ? null : mobileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.CERTUID
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.CERTUID
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getCertuid() {
        return certuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.CERTUID
     *
     * @param certuid the value for OSOADATA.T_ACCEPTED_CERT_INFO.CERTUID
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setCertuid(String certuid) {
        this.certuid = certuid == null ? null : certuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BRANCHNO
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.BRANCHNO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getBranchno() {
        return branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BRANCHNO
     *
     * @param branchno the value for OSOADATA.T_ACCEPTED_CERT_INFO.BRANCHNO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setBranchno(String branchno) {
        this.branchno = branchno == null ? null : branchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.POSTID
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.POSTID
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.POSTID
     *
     * @param postid the value for OSOADATA.T_ACCEPTED_CERT_INFO.POSTID
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setPostid(String postid) {
        this.postid = postid == null ? null : postid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.ADDR
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.ADDR
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.ADDR
     *
     * @param addr the value for OSOADATA.T_ACCEPTED_CERT_INFO.ADDR
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.STATE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.STATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.STATE
     *
     * @param state the value for OSOADATA.T_ACCEPTED_CERT_INFO.STATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.CREATEDATE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.CREATEDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.CREATEDATE
     *
     * @param createdate the value for OSOADATA.T_ACCEPTED_CERT_INFO.CREATEDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.USERSEX
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.USERSEX
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.USERSEX
     *
     * @param usersex the value for OSOADATA.T_ACCEPTED_CERT_INFO.USERSEX
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setUsersex(String usersex) {
        this.usersex = usersex == null ? null : usersex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BORTHDAY
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.BORTHDAY
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getBorthday() {
        return borthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BORTHDAY
     *
     * @param borthday the value for OSOADATA.T_ACCEPTED_CERT_INFO.BORTHDAY
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setBorthday(String borthday) {
        this.borthday = borthday == null ? null : borthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.NATIONALITY
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.NATIONALITY
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.NATIONALITY
     *
     * @param nationality the value for OSOADATA.T_ACCEPTED_CERT_INFO.NATIONALITY
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDBEGINDATE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.IDBEGINDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getIdbegindate() {
        return idbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDBEGINDATE
     *
     * @param idbegindate the value for OSOADATA.T_ACCEPTED_CERT_INFO.IDBEGINDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setIdbegindate(String idbegindate) {
        this.idbegindate = idbegindate == null ? null : idbegindate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDENDDATE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.IDENDDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getIdenddate() {
        return idenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IDENDDATE
     *
     * @param idenddate the value for OSOADATA.T_ACCEPTED_CERT_INFO.IDENDDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setIdenddate(String idenddate) {
        this.idenddate = idenddate == null ? null : idenddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBILENO1
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBILENO1
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getBkmobileno1() {
        return bkmobileno1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBILENO1
     *
     * @param bkmobileno1 the value for OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBILENO1
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setBkmobileno1(String bkmobileno1) {
        this.bkmobileno1 = bkmobileno1 == null ? null : bkmobileno1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.UPDATEDATE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.UPDATEDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.UPDATEDATE
     *
     * @param updatedate the value for OSOADATA.T_ACCEPTED_CERT_INFO.UPDATEDATE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setUpdatedate(String updatedate) {
        this.updatedate = updatedate == null ? null : updatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.POLICEORG
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.POLICEORG
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getPoliceorg() {
        return policeorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.POLICEORG
     *
     * @param policeorg the value for OSOADATA.T_ACCEPTED_CERT_INFO.POLICEORG
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setPoliceorg(String policeorg) {
        this.policeorg = policeorg == null ? null : policeorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.NATIVE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.NATIVE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getNatives() {
        return natives;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.NATIVE
     *
     * @param //native the value for OSOADATA.T_ACCEPTED_CERT_INFO.NATIVE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setNatives(String natives) {
        this.natives = natives == null ? null : natives.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.RISKEXP
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.RISKEXP
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getRiskexp() {
        return riskexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.RISKEXP
     *
     * @param riskexp the value for OSOADATA.T_ACCEPTED_CERT_INFO.RISKEXP
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setRiskexp(String riskexp) {
        this.riskexp = riskexp == null ? null : riskexp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.ACCESS_CHANNEL
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.ACCESS_CHANNEL
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public Integer getAccessChannel() {
        return accessChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.ACCESS_CHANNEL
     *
     * @param accessChannel the value for OSOADATA.T_ACCEPTED_CERT_INFO.ACCESS_CHANNEL
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setAccessChannel(Integer accessChannel) {
        this.accessChannel = accessChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IPADDR
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.IPADDR
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.IPADDR
     *
     * @param ipaddr the value for OSOADATA.T_ACCEPTED_CERT_INFO.IPADDR
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr == null ? null : ipaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.MACADDR
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.MACADDR
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getMacaddr() {
        return macaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.MACADDR
     *
     * @param macaddr the value for OSOADATA.T_ACCEPTED_CERT_INFO.MACADDR
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setMacaddr(String macaddr) {
        this.macaddr = macaddr == null ? null : macaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_SOURCE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_SOURCE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getExtendSource() {
        return extendSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_SOURCE
     *
     * @param extendSource the value for OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_SOURCE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setExtendSource(String extendSource) {
        this.extendSource = extendSource == null ? null : extendSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_COMPANY
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_COMPANY
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getExtendCompany() {
        return extendCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_COMPANY
     *
     * @param extendCompany the value for OSOADATA.T_ACCEPTED_CERT_INFO.EXTEND_COMPANY
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setExtendCompany(String extendCompany) {
        this.extendCompany = extendCompany == null ? null : extendCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BANKTYPE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.BANKTYPE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getBanktype() {
        return banktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BANKTYPE
     *
     * @param banktype the value for OSOADATA.T_ACCEPTED_CERT_INFO.BANKTYPE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setBanktype(String banktype) {
        this.banktype = banktype == null ? null : banktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BANKCODE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.BANKCODE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BANKCODE
     *
     * @param bankcode the value for OSOADATA.T_ACCEPTED_CERT_INFO.BANKCODE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.INFOCOLECT_CHANNEL
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.INFOCOLECT_CHANNEL
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getInfocolectChannel() {
        return infocolectChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.INFOCOLECT_CHANNEL
     *
     * @param infocolectChannel the value for OSOADATA.T_ACCEPTED_CERT_INFO.INFOCOLECT_CHANNEL
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setInfocolectChannel(String infocolectChannel) {
        this.infocolectChannel = infocolectChannel == null ? null : infocolectChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.EDU
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.EDU
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getEdu() {
        return edu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.EDU
     *
     * @param edu the value for OSOADATA.T_ACCEPTED_CERT_INFO.EDU
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setEdu(String edu) {
        this.edu = edu == null ? null : edu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.PROFESSION_CODE
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.PROFESSION_CODE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getProfessionCode() {
        return professionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.PROFESSION_CODE
     *
     * @param professionCode the value for OSOADATA.T_ACCEPTED_CERT_INFO.PROFESSION_CODE
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setProfessionCode(String professionCode) {
        this.professionCode = professionCode == null ? null : professionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.OPACCTKIND_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.OPACCTKIND_FLAG
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getOpacctkindFlag() {
        return opacctkindFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.OPACCTKIND_FLAG
     *
     * @param opacctkindFlag the value for OSOADATA.T_ACCEPTED_CERT_INFO.OPACCTKIND_FLAG
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setOpacctkindFlag(String opacctkindFlag) {
        this.opacctkindFlag = opacctkindFlag == null ? null : opacctkindFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBLIENO1
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBLIENO1
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getBkmoblieno1() {
        return bkmoblieno1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBLIENO1
     *
     * @param bkmoblieno1 the value for OSOADATA.T_ACCEPTED_CERT_INFO.BKMOBLIENO1
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setBkmoblieno1(String bkmoblieno1) {
        this.bkmoblieno1 = bkmoblieno1 == null ? null : bkmoblieno1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.RECOMMENDNO
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.RECOMMENDNO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public String getRecommendno() {
        return recommendno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.RECOMMENDNO
     *
     * @param recommendno the value for OSOADATA.T_ACCEPTED_CERT_INFO.RECOMMENDNO
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setRecommendno(String recommendno) {
        this.recommendno = recommendno == null ? null : recommendno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.COMMISSION
     *
     * @return the value of OSOADATA.T_ACCEPTED_CERT_INFO.COMMISSION
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public Double getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_CERT_INFO.COMMISSION
     *
     * @param commission the value for OSOADATA.T_ACCEPTED_CERT_INFO.COMMISSION
     *
     * @mbggenerated Wed Aug 03 17:58:07 CST 2016
     */
    public void setCommission(Double commission) {
        this.commission = commission;
    }

    @Override
    public String toString() {
        return "AcceptedCertInfo{" +
                "id=" + id +
                ", custname='" + custname + '\'' +
                ", idtype='" + idtype + '\'' +
                ", idno='" + idno + '\'' +
                ", ethnic='" + ethnic + '\'' +
                ", mobileno='" + mobileno + '\'' +
                ", certuid='" + certuid + '\'' +
                ", branchno='" + branchno + '\'' +
                ", postid='" + postid + '\'' +
                ", addr='" + addr + '\'' +
                ", state='" + state + '\'' +
                ", createdate='" + createdate + '\'' +
                ", usersex='" + usersex + '\'' +
                ", borthday='" + borthday + '\'' +
                ", nationality='" + nationality + '\'' +
                ", idbegindate='" + idbegindate + '\'' +
                ", idenddate='" + idenddate + '\'' +
                ", bkmobileno1='" + bkmobileno1 + '\'' +
                ", updatedate='" + updatedate + '\'' +
                ", policeorg='" + policeorg + '\'' +
                ", riskexp='" + riskexp + '\'' +
                ", accessChannel=" + accessChannel +
                ", ipaddr='" + ipaddr + '\'' +
                ", macaddr='" + macaddr + '\'' +
                ", extendSource='" + extendSource + '\'' +
                ", extendCompany='" + extendCompany + '\'' +
                ", banktype='" + banktype + '\'' +
                ", bankcode='" + bankcode + '\'' +
                ", infocolectChannel='" + infocolectChannel + '\'' +
                ", edu='" + edu + '\'' +
                ", professionCode='" + professionCode + '\'' +
                ", opacctkindFlag='" + opacctkindFlag + '\'' +
                ", bkmoblieno1='" + bkmoblieno1 + '\'' +
                ", recommendno='" + recommendno + '\'' +
                ", commission=" + commission +
                '}';
    }
}