package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@Table(name = "T_ACCEPTED_SCHEDULE")
public class AcceptedSchedule {

    public static final String state_0 = "0";//0:正常
    public static final String state_1 = "1";//1:已驳回
    public static final String state_3 = "3";//1:已驳回
    public static final String state_4 = "4";//4:已修复

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.ID
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.USER_ID
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.MGR_ID
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String mgrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.STATE
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.BUSINESS
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.CURRENT_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String currentStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.SENDWAY
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String sendway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.START_TIME
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.BACK_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String backStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.FAOPEN_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String faopenStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.UPLOADIMG_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String uploadimgFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.IDCONFIRM_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String idconfirmFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.WITNESS_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String witnessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.CERTINTALL_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String certintallFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.CAPITALACCT_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String capitalacctFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.STKACCT_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String stkacctFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.OPFNDACCT_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String opfndacctFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.SETPWD_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String setpwdFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.TPBANK_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String tpbankFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.RISKSURVEY_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String risksurveyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.VISITSURVEY_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String visitsurveyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.LASTCOMPLETE_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String lastcompleteStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SCHEDULE.REJECT_RESON
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    private String rejectReson;

    @Transient
    private String step;
    @Transient
    private String source;
    @Transient
    private String mobileno;

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getMobileno() {
        return mobileno;
    }

    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }

    public String getStep() {
        return step;
    }

    public void setStep(String step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.ID
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.ID
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.ID
     *
     * @param id the value for OSOADATA.T_ACCEPTED_SCHEDULE.ID
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.USER_ID
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.USER_ID
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.USER_ID
     *
     * @param userId the value for OSOADATA.T_ACCEPTED_SCHEDULE.USER_ID
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.MGR_ID
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.MGR_ID
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getMgrId() {
        return mgrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.MGR_ID
     *
     * @param mgrId the value for OSOADATA.T_ACCEPTED_SCHEDULE.MGR_ID
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setMgrId(String mgrId) {
        this.mgrId = mgrId == null ? null : mgrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.STATE
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.STATE
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.STATE
     *
     * @param state the value for OSOADATA.T_ACCEPTED_SCHEDULE.STATE
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.BUSINESS
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.BUSINESS
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.BUSINESS
     *
     * @param business the value for OSOADATA.T_ACCEPTED_SCHEDULE.BUSINESS
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.CURRENT_STEP
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.CURRENT_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getCurrentStep() {
        return currentStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.CURRENT_STEP
     *
     * @param currentStep the value for OSOADATA.T_ACCEPTED_SCHEDULE.CURRENT_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setCurrentStep(String currentStep) {
        this.currentStep = currentStep == null ? null : currentStep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.SENDWAY
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.SENDWAY
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getSendway() {
        return sendway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.SENDWAY
     *
     * @param sendway the value for OSOADATA.T_ACCEPTED_SCHEDULE.SENDWAY
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setSendway(String sendway) {
        this.sendway = sendway == null ? null : sendway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.START_TIME
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.START_TIME
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.START_TIME
     *
     * @param startTime the value for OSOADATA.T_ACCEPTED_SCHEDULE.START_TIME
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.UPDATE_TIME
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.UPDATE_TIME
     *
     * @param updateTime the value for OSOADATA.T_ACCEPTED_SCHEDULE.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.BACK_STEP
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.BACK_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getBackStep() {
        return backStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.BACK_STEP
     *
     * @param backStep the value for OSOADATA.T_ACCEPTED_SCHEDULE.BACK_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setBackStep(String backStep) {
        this.backStep = backStep == null ? null : backStep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.FAOPEN_STEP
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.FAOPEN_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getFaopenStep() {
        return faopenStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.FAOPEN_STEP
     *
     * @param faopenStep the value for OSOADATA.T_ACCEPTED_SCHEDULE.FAOPEN_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setFaopenStep(String faopenStep) {
        this.faopenStep = faopenStep == null ? null : faopenStep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.UPLOADIMG_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.UPLOADIMG_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getUploadimgFlag() {
        return uploadimgFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.UPLOADIMG_FLAG
     *
     * @param uploadimgFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.UPLOADIMG_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setUploadimgFlag(String uploadimgFlag) {
        this.uploadimgFlag = uploadimgFlag == null ? null : uploadimgFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.IDCONFIRM_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.IDCONFIRM_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getIdconfirmFlag() {
        return idconfirmFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.IDCONFIRM_FLAG
     *
     * @param idconfirmFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.IDCONFIRM_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setIdconfirmFlag(String idconfirmFlag) {
        this.idconfirmFlag = idconfirmFlag == null ? null : idconfirmFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.WITNESS_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.WITNESS_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getWitnessFlag() {
        return witnessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.WITNESS_FLAG
     *
     * @param witnessFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.WITNESS_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setWitnessFlag(String witnessFlag) {
        this.witnessFlag = witnessFlag == null ? null : witnessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.CERTINTALL_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.CERTINTALL_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getCertintallFlag() {
        return certintallFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.CERTINTALL_FLAG
     *
     * @param certintallFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.CERTINTALL_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setCertintallFlag(String certintallFlag) {
        this.certintallFlag = certintallFlag == null ? null : certintallFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.CAPITALACCT_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.CAPITALACCT_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getCapitalacctFlag() {
        return capitalacctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.CAPITALACCT_FLAG
     *
     * @param capitalacctFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.CAPITALACCT_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setCapitalacctFlag(String capitalacctFlag) {
        this.capitalacctFlag = capitalacctFlag == null ? null : capitalacctFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.STKACCT_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.STKACCT_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getStkacctFlag() {
        return stkacctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.STKACCT_FLAG
     *
     * @param stkacctFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.STKACCT_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setStkacctFlag(String stkacctFlag) {
        this.stkacctFlag = stkacctFlag == null ? null : stkacctFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.OPFNDACCT_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.OPFNDACCT_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getOpfndacctFlag() {
        return opfndacctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.OPFNDACCT_FLAG
     *
     * @param opfndacctFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.OPFNDACCT_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setOpfndacctFlag(String opfndacctFlag) {
        this.opfndacctFlag = opfndacctFlag == null ? null : opfndacctFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.SETPWD_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.SETPWD_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getSetpwdFlag() {
        return setpwdFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.SETPWD_FLAG
     *
     * @param setpwdFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.SETPWD_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setSetpwdFlag(String setpwdFlag) {
        this.setpwdFlag = setpwdFlag == null ? null : setpwdFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.TPBANK_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.TPBANK_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getTpbankFlag() {
        return tpbankFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.TPBANK_FLAG
     *
     * @param tpbankFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.TPBANK_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setTpbankFlag(String tpbankFlag) {
        this.tpbankFlag = tpbankFlag == null ? null : tpbankFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.RISKSURVEY_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.RISKSURVEY_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getRisksurveyFlag() {
        return risksurveyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.RISKSURVEY_FLAG
     *
     * @param risksurveyFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.RISKSURVEY_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setRisksurveyFlag(String risksurveyFlag) {
        this.risksurveyFlag = risksurveyFlag == null ? null : risksurveyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.VISITSURVEY_FLAG
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.VISITSURVEY_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getVisitsurveyFlag() {
        return visitsurveyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.VISITSURVEY_FLAG
     *
     * @param visitsurveyFlag the value for OSOADATA.T_ACCEPTED_SCHEDULE.VISITSURVEY_FLAG
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setVisitsurveyFlag(String visitsurveyFlag) {
        this.visitsurveyFlag = visitsurveyFlag == null ? null : visitsurveyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.LASTCOMPLETE_STEP
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.LASTCOMPLETE_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getLastcompleteStep() {
        return lastcompleteStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.LASTCOMPLETE_STEP
     *
     * @param lastcompleteStep the value for OSOADATA.T_ACCEPTED_SCHEDULE.LASTCOMPLETE_STEP
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setLastcompleteStep(String lastcompleteStep) {
        this.lastcompleteStep = lastcompleteStep == null ? null : lastcompleteStep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.REJECT_RESON
     *
     * @return the value of OSOADATA.T_ACCEPTED_SCHEDULE.REJECT_RESON
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public String getRejectReson() {
        return rejectReson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SCHEDULE.REJECT_RESON
     *
     * @param rejectReson the value for OSOADATA.T_ACCEPTED_SCHEDULE.REJECT_RESON
     *
     * @mbggenerated Mon Aug 15 08:44:36 CST 2016
     */
    public void setRejectReson(String rejectReson) {
        this.rejectReson = rejectReson == null ? null : rejectReson.trim();
    }

    @Override
    public String toString() {
        return "AcceptedSchedule{" +
                "id='" + id + '\'' +
                ", userId='" + userId + '\'' +
                ", mgrId='" + mgrId + '\'' +
                ", state='" + state + '\'' +
                ", business='" + business + '\'' +
                ", currentStep='" + currentStep + '\'' +
                ", sendway='" + sendway + '\'' +
                ", startTime='" + startTime + '\'' +
                ", updateTime='" + updateTime + '\'' +
                ", backStep='" + backStep + '\'' +
                ", faopenStep='" + faopenStep + '\'' +
                ", uploadimgFlag='" + uploadimgFlag + '\'' +
                ", idconfirmFlag='" + idconfirmFlag + '\'' +
                ", witnessFlag='" + witnessFlag + '\'' +
                ", certintallFlag='" + certintallFlag + '\'' +
                ", capitalacctFlag='" + capitalacctFlag + '\'' +
                ", stkacctFlag='" + stkacctFlag + '\'' +
                ", opfndacctFlag='" + opfndacctFlag + '\'' +
                ", setpwdFlag='" + setpwdFlag + '\'' +
                ", tpbankFlag='" + tpbankFlag + '\'' +
                ", risksurveyFlag='" + risksurveyFlag + '\'' +
                ", visitsurveyFlag='" + visitsurveyFlag + '\'' +
                ", lastcompleteStep='" + lastcompleteStep + '\'' +
                ", rejectReson='" + rejectReson + '\'' +
                '}';
    }
}