package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "T_ACCEPTED_SMS_LIMIT")
public class AcceptedSmsLimit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.CLIENT_SOURCE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    @Id
    private String clientSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.MOBILE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_COUNT
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    private Integer sendCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.MSG_CODE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    private String msgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_DATE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    private String sendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.MSGCODE_STATE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    private String msgcodeState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.CLIENT_SOURCE
     *
     * @return the value of OSOADATA.T_ACCEPTED_SMS_LIMIT.CLIENT_SOURCE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public String getClientSource() {
        return clientSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.CLIENT_SOURCE
     *
     * @param clientSource the value for OSOADATA.T_ACCEPTED_SMS_LIMIT.CLIENT_SOURCE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public void setClientSource(String clientSource) {
        this.clientSource = clientSource == null ? null : clientSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.MOBILE
     *
     * @return the value of OSOADATA.T_ACCEPTED_SMS_LIMIT.MOBILE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.MOBILE
     *
     * @param mobile the value for OSOADATA.T_ACCEPTED_SMS_LIMIT.MOBILE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_COUNT
     *
     * @return the value of OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_COUNT
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public Integer getSendCount() {
        return sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_COUNT
     *
     * @param sendCount the value for OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_COUNT
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public void setSendCount(Integer sendCount) {
        this.sendCount = sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.MSG_CODE
     *
     * @return the value of OSOADATA.T_ACCEPTED_SMS_LIMIT.MSG_CODE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public String getMsgCode() {
        return msgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.MSG_CODE
     *
     * @param msgCode the value for OSOADATA.T_ACCEPTED_SMS_LIMIT.MSG_CODE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public void setMsgCode(String msgCode) {
        this.msgCode = msgCode == null ? null : msgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_DATE
     *
     * @return the value of OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_DATE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public String getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_DATE
     *
     * @param sendDate the value for OSOADATA.T_ACCEPTED_SMS_LIMIT.SEND_DATE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public void setSendDate(String sendDate) {
        this.sendDate = sendDate == null ? null : sendDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.MSGCODE_STATE
     *
     * @return the value of OSOADATA.T_ACCEPTED_SMS_LIMIT.MSGCODE_STATE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public String getMsgcodeState() {
        return msgcodeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ACCEPTED_SMS_LIMIT.MSGCODE_STATE
     *
     * @param msgcodeState the value for OSOADATA.T_ACCEPTED_SMS_LIMIT.MSGCODE_STATE
     *
     * @mbggenerated Wed Aug 10 14:56:27 CST 2016
     */
    public void setMsgcodeState(String msgcodeState) {
        this.msgcodeState = msgcodeState == null ? null : msgcodeState.trim();
    }

    @Override
    public String toString() {
        return "AcceptedSmsLimit{" +
                "clientSource='" + clientSource + '\'' +
                ", mobile='" + mobile + '\'' +
                ", sendCount=" + sendCount +
                ", msgCode='" + msgCode + '\'' +
                ", sendDate='" + sendDate + '\'' +
                ", msgcodeState='" + msgcodeState + '\'' +
                '}';
    }
}