package com.app.sjkh.pojo.local;

import javax.persistence.Id;

public class BBranch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.BRANCHNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    @Id
    private String branchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.BRANCHNAME
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String branchname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.BRANCHCODE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String branchcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.ORDERNUM
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.ISDISPLAY
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String isdisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.REGIONNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String regionno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.PROVINCENO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String provinceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.CITYNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String cityno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.ADDRESS
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.TRAINFO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String trainfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.LAT
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.LNT
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String lnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.ZOOM
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private Integer zoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.COMPANYNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String companyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.MAXZOOM
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private Integer maxzoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.SZ_SITE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String szSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.SH_SITE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String shSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.XW_SHA
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String xwSha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.XW_SHB
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String xwShb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.JS_SHA
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String jsSha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.JS_SHB
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String jsShb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.KH_SHA
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String khSha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.KH_SHB
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String khShb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.CUACCT_CLS
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String cuacctCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.CUST_CODE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String custCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.CUST_PWD
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String custPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BRANCH.INTRO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.BRANCHNO
     *
     * @return the value of OSOADATA.T_B_BRANCH.BRANCHNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getBranchno() {
        return branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.BRANCHNO
     *
     * @param branchno the value for OSOADATA.T_B_BRANCH.BRANCHNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setBranchno(String branchno) {
        this.branchno = branchno == null ? null : branchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.BRANCHNAME
     *
     * @return the value of OSOADATA.T_B_BRANCH.BRANCHNAME
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getBranchname() {
        return branchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.BRANCHNAME
     *
     * @param branchname the value for OSOADATA.T_B_BRANCH.BRANCHNAME
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setBranchname(String branchname) {
        this.branchname = branchname == null ? null : branchname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.BRANCHCODE
     *
     * @return the value of OSOADATA.T_B_BRANCH.BRANCHCODE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getBranchcode() {
        return branchcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.BRANCHCODE
     *
     * @param branchcode the value for OSOADATA.T_B_BRANCH.BRANCHCODE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode == null ? null : branchcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.ORDERNUM
     *
     * @return the value of OSOADATA.T_B_BRANCH.ORDERNUM
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.ORDERNUM
     *
     * @param ordernum the value for OSOADATA.T_B_BRANCH.ORDERNUM
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setOrdernum(String ordernum) {
        this.ordernum = ordernum == null ? null : ordernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.ISDISPLAY
     *
     * @return the value of OSOADATA.T_B_BRANCH.ISDISPLAY
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getIsdisplay() {
        return isdisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.ISDISPLAY
     *
     * @param isdisplay the value for OSOADATA.T_B_BRANCH.ISDISPLAY
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setIsdisplay(String isdisplay) {
        this.isdisplay = isdisplay == null ? null : isdisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.REGIONNO
     *
     * @return the value of OSOADATA.T_B_BRANCH.REGIONNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getRegionno() {
        return regionno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.REGIONNO
     *
     * @param regionno the value for OSOADATA.T_B_BRANCH.REGIONNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setRegionno(String regionno) {
        this.regionno = regionno == null ? null : regionno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.PROVINCENO
     *
     * @return the value of OSOADATA.T_B_BRANCH.PROVINCENO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getProvinceno() {
        return provinceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.PROVINCENO
     *
     * @param provinceno the value for OSOADATA.T_B_BRANCH.PROVINCENO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setProvinceno(String provinceno) {
        this.provinceno = provinceno == null ? null : provinceno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.CITYNO
     *
     * @return the value of OSOADATA.T_B_BRANCH.CITYNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getCityno() {
        return cityno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.CITYNO
     *
     * @param cityno the value for OSOADATA.T_B_BRANCH.CITYNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setCityno(String cityno) {
        this.cityno = cityno == null ? null : cityno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.ADDRESS
     *
     * @return the value of OSOADATA.T_B_BRANCH.ADDRESS
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.ADDRESS
     *
     * @param address the value for OSOADATA.T_B_BRANCH.ADDRESS
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.TRAINFO
     *
     * @return the value of OSOADATA.T_B_BRANCH.TRAINFO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getTrainfo() {
        return trainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.TRAINFO
     *
     * @param trainfo the value for OSOADATA.T_B_BRANCH.TRAINFO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setTrainfo(String trainfo) {
        this.trainfo = trainfo == null ? null : trainfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.LAT
     *
     * @return the value of OSOADATA.T_B_BRANCH.LAT
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.LAT
     *
     * @param lat the value for OSOADATA.T_B_BRANCH.LAT
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.LNT
     *
     * @return the value of OSOADATA.T_B_BRANCH.LNT
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getLnt() {
        return lnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.LNT
     *
     * @param lnt the value for OSOADATA.T_B_BRANCH.LNT
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setLnt(String lnt) {
        this.lnt = lnt == null ? null : lnt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.ZOOM
     *
     * @return the value of OSOADATA.T_B_BRANCH.ZOOM
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public Integer getZoom() {
        return zoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.ZOOM
     *
     * @param zoom the value for OSOADATA.T_B_BRANCH.ZOOM
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setZoom(Integer zoom) {
        this.zoom = zoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.COMPANYNO
     *
     * @return the value of OSOADATA.T_B_BRANCH.COMPANYNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getCompanyno() {
        return companyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.COMPANYNO
     *
     * @param companyno the value for OSOADATA.T_B_BRANCH.COMPANYNO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setCompanyno(String companyno) {
        this.companyno = companyno == null ? null : companyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.MAXZOOM
     *
     * @return the value of OSOADATA.T_B_BRANCH.MAXZOOM
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public Integer getMaxzoom() {
        return maxzoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.MAXZOOM
     *
     * @param maxzoom the value for OSOADATA.T_B_BRANCH.MAXZOOM
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setMaxzoom(Integer maxzoom) {
        this.maxzoom = maxzoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.SZ_SITE
     *
     * @return the value of OSOADATA.T_B_BRANCH.SZ_SITE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getSzSite() {
        return szSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.SZ_SITE
     *
     * @param szSite the value for OSOADATA.T_B_BRANCH.SZ_SITE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setSzSite(String szSite) {
        this.szSite = szSite == null ? null : szSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.SH_SITE
     *
     * @return the value of OSOADATA.T_B_BRANCH.SH_SITE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getShSite() {
        return shSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.SH_SITE
     *
     * @param shSite the value for OSOADATA.T_B_BRANCH.SH_SITE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setShSite(String shSite) {
        this.shSite = shSite == null ? null : shSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.XW_SHA
     *
     * @return the value of OSOADATA.T_B_BRANCH.XW_SHA
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getXwSha() {
        return xwSha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.XW_SHA
     *
     * @param xwSha the value for OSOADATA.T_B_BRANCH.XW_SHA
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setXwSha(String xwSha) {
        this.xwSha = xwSha == null ? null : xwSha.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.XW_SHB
     *
     * @return the value of OSOADATA.T_B_BRANCH.XW_SHB
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getXwShb() {
        return xwShb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.XW_SHB
     *
     * @param xwShb the value for OSOADATA.T_B_BRANCH.XW_SHB
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setXwShb(String xwShb) {
        this.xwShb = xwShb == null ? null : xwShb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.JS_SHA
     *
     * @return the value of OSOADATA.T_B_BRANCH.JS_SHA
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getJsSha() {
        return jsSha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.JS_SHA
     *
     * @param jsSha the value for OSOADATA.T_B_BRANCH.JS_SHA
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setJsSha(String jsSha) {
        this.jsSha = jsSha == null ? null : jsSha.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.JS_SHB
     *
     * @return the value of OSOADATA.T_B_BRANCH.JS_SHB
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getJsShb() {
        return jsShb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.JS_SHB
     *
     * @param jsShb the value for OSOADATA.T_B_BRANCH.JS_SHB
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setJsShb(String jsShb) {
        this.jsShb = jsShb == null ? null : jsShb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.KH_SHA
     *
     * @return the value of OSOADATA.T_B_BRANCH.KH_SHA
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getKhSha() {
        return khSha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.KH_SHA
     *
     * @param khSha the value for OSOADATA.T_B_BRANCH.KH_SHA
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setKhSha(String khSha) {
        this.khSha = khSha == null ? null : khSha.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.KH_SHB
     *
     * @return the value of OSOADATA.T_B_BRANCH.KH_SHB
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getKhShb() {
        return khShb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.KH_SHB
     *
     * @param khShb the value for OSOADATA.T_B_BRANCH.KH_SHB
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setKhShb(String khShb) {
        this.khShb = khShb == null ? null : khShb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.CUACCT_CLS
     *
     * @return the value of OSOADATA.T_B_BRANCH.CUACCT_CLS
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getCuacctCls() {
        return cuacctCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.CUACCT_CLS
     *
     * @param cuacctCls the value for OSOADATA.T_B_BRANCH.CUACCT_CLS
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setCuacctCls(String cuacctCls) {
        this.cuacctCls = cuacctCls == null ? null : cuacctCls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.CUST_CODE
     *
     * @return the value of OSOADATA.T_B_BRANCH.CUST_CODE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.CUST_CODE
     *
     * @param custCode the value for OSOADATA.T_B_BRANCH.CUST_CODE
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setCustCode(String custCode) {
        this.custCode = custCode == null ? null : custCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.CUST_PWD
     *
     * @return the value of OSOADATA.T_B_BRANCH.CUST_PWD
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getCustPwd() {
        return custPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.CUST_PWD
     *
     * @param custPwd the value for OSOADATA.T_B_BRANCH.CUST_PWD
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setCustPwd(String custPwd) {
        this.custPwd = custPwd == null ? null : custPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BRANCH.INTRO
     *
     * @return the value of OSOADATA.T_B_BRANCH.INTRO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BRANCH.INTRO
     *
     * @param intro the value for OSOADATA.T_B_BRANCH.INTRO
     *
     * @mbggenerated Mon Aug 22 14:26:00 CST 2016
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}