package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "T_B_BUSINESS_LOG")
public class BBusinessLog {
    /** 日志类型,短信 */
    public static final String LogTypeSms = "sms";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.ID
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.OPERATOR_ID
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.LOG_TYPE
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.INPUT_PARAM
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String inputParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.BEGINTIME
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.ENDTIME
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.ERR_NO
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String errNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.ERR_MSG
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String errMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.IP
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.MAC
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.OPWAY
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String opway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.OPERATOR_NAME
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_BUSINESS_LOG.COMPANY
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    private String company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.ID
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.ID
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.ID
     *
     * @param id the value for OSOADATA.T_B_BUSINESS_LOG.ID
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.OPERATOR_ID
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.OPERATOR_ID
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.OPERATOR_ID
     *
     * @param operatorId the value for OSOADATA.T_B_BUSINESS_LOG.OPERATOR_ID
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.LOG_TYPE
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.LOG_TYPE
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.LOG_TYPE
     *
     * @param logType the value for OSOADATA.T_B_BUSINESS_LOG.LOG_TYPE
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setLogType(String logType) {
        this.logType = logType == null ? null : logType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.INPUT_PARAM
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.INPUT_PARAM
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getInputParam() {
        return inputParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.INPUT_PARAM
     *
     * @param inputParam the value for OSOADATA.T_B_BUSINESS_LOG.INPUT_PARAM
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setInputParam(String inputParam) {
        this.inputParam = inputParam == null ? null : inputParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.BEGINTIME
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.BEGINTIME
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.BEGINTIME
     *
     * @param begintime the value for OSOADATA.T_B_BUSINESS_LOG.BEGINTIME
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setBegintime(String begintime) {
        this.begintime = begintime == null ? null : begintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.ENDTIME
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.ENDTIME
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.ENDTIME
     *
     * @param endtime the value for OSOADATA.T_B_BUSINESS_LOG.ENDTIME
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.ERR_NO
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.ERR_NO
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getErrNo() {
        return errNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.ERR_NO
     *
     * @param errNo the value for OSOADATA.T_B_BUSINESS_LOG.ERR_NO
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setErrNo(String errNo) {
        this.errNo = errNo == null ? null : errNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.ERR_MSG
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.ERR_MSG
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.ERR_MSG
     *
     * @param errMsg the value for OSOADATA.T_B_BUSINESS_LOG.ERR_MSG
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg == null ? null : errMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.IP
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.IP
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.IP
     *
     * @param ip the value for OSOADATA.T_B_BUSINESS_LOG.IP
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.MAC
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.MAC
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.MAC
     *
     * @param mac the value for OSOADATA.T_B_BUSINESS_LOG.MAC
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.OPWAY
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.OPWAY
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getOpway() {
        return opway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.OPWAY
     *
     * @param opway the value for OSOADATA.T_B_BUSINESS_LOG.OPWAY
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setOpway(String opway) {
        this.opway = opway == null ? null : opway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.OPERATOR_NAME
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.OPERATOR_NAME
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.OPERATOR_NAME
     *
     * @param operatorName the value for OSOADATA.T_B_BUSINESS_LOG.OPERATOR_NAME
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_BUSINESS_LOG.COMPANY
     *
     * @return the value of OSOADATA.T_B_BUSINESS_LOG.COMPANY
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_BUSINESS_LOG.COMPANY
     *
     * @param company the value for OSOADATA.T_B_BUSINESS_LOG.COMPANY
     *
     * @mbggenerated Wed Aug 10 16:27:02 CST 2016
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    @Override
    public String toString() {
        return "BBusinessLog{" +
                "id='" + id + '\'' +
                ", operatorId='" + operatorId + '\'' +
                ", logType='" + logType + '\'' +
                ", inputParam='" + inputParam + '\'' +
                ", begintime='" + begintime + '\'' +
                ", endtime='" + endtime + '\'' +
                ", errNo='" + errNo + '\'' +
                ", errMsg='" + errMsg + '\'' +
                ", ip='" + ip + '\'' +
                ", mac='" + mac + '\'' +
                ", opway='" + opway + '\'' +
                ", operatorName='" + operatorName + '\'' +
                ", company='" + company + '\'' +
                '}';
    }
}