package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;

//@Alias("bPost")
@Table(name = "T_B_POST")
public class BPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_POST.ID
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_POST.POST
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_POST.PROVINCE
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_POST.MUNICIPALITY
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    private String municipality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_B_POST.DISTRICT
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    private String district;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_POST.ID
     *
     * @return the value of OSOADATA.T_B_POST.ID
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_POST.ID
     *
     * @param id the value for OSOADATA.T_B_POST.ID
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_POST.POST
     *
     * @return the value of OSOADATA.T_B_POST.POST
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_POST.POST
     *
     * @param post the value for OSOADATA.T_B_POST.POST
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_POST.PROVINCE
     *
     * @return the value of OSOADATA.T_B_POST.PROVINCE
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_POST.PROVINCE
     *
     * @param province the value for OSOADATA.T_B_POST.PROVINCE
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_POST.MUNICIPALITY
     *
     * @return the value of OSOADATA.T_B_POST.MUNICIPALITY
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public String getMunicipality() {
        return municipality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_POST.MUNICIPALITY
     *
     * @param municipality the value for OSOADATA.T_B_POST.MUNICIPALITY
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public void setMunicipality(String municipality) {
        this.municipality = municipality == null ? null : municipality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_B_POST.DISTRICT
     *
     * @return the value of OSOADATA.T_B_POST.DISTRICT
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_B_POST.DISTRICT
     *
     * @param district the value for OSOADATA.T_B_POST.DISTRICT
     *
     * @mbggenerated Mon Aug 15 10:26:54 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    @Override
    public String toString() {
        return "BPost{" +
                "id=" + id +
                ", post='" + post + '\'' +
                ", province='" + province + '\'' +
                ", municipality='" + municipality + '\'' +
                ", district='" + district + '\'' +
                '}';
    }
}