package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "HBEC_APPTOOLS.T_Customer_Service_Branch")
public class CustomerServiceBranch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.MOBILENO
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    @Id
    private String mobileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CLIENT_ID
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CHANNEL
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.BRANCHNO
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    private String branchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.REQTIME
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    private String reqtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.UPDATETIME
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCLIENTIDFLG
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    private String synclientidflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCRMFLG
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    private String syncrmflg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.MOBILENO
     *
     * @return the value of HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.MOBILENO
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public String getMobileno() {
        return mobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.MOBILENO
     *
     * @param mobileno the value for HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.MOBILENO
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno == null ? null : mobileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CLIENT_ID
     *
     * @return the value of HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CLIENT_ID
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CLIENT_ID
     *
     * @param clientId the value for HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CLIENT_ID
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CHANNEL
     *
     * @return the value of HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CHANNEL
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CHANNEL
     *
     * @param channel the value for HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.CHANNEL
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.BRANCHNO
     *
     * @return the value of HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.BRANCHNO
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public String getBranchno() {
        return branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.BRANCHNO
     *
     * @param branchno the value for HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.BRANCHNO
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public void setBranchno(String branchno) {
        this.branchno = branchno == null ? null : branchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.REQTIME
     *
     * @return the value of HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.REQTIME
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public String getReqtime() {
        return reqtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.REQTIME
     *
     * @param reqtime the value for HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.REQTIME
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public void setReqtime(String reqtime) {
        this.reqtime = reqtime == null ? null : reqtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.UPDATETIME
     *
     * @return the value of HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.UPDATETIME
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.UPDATETIME
     *
     * @param updatetime the value for HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.UPDATETIME
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCLIENTIDFLG
     *
     * @return the value of HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCLIENTIDFLG
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public String getSynclientidflg() {
        return synclientidflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCLIENTIDFLG
     *
     * @param synclientidflg the value for HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCLIENTIDFLG
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public void setSynclientidflg(String synclientidflg) {
        this.synclientidflg = synclientidflg == null ? null : synclientidflg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCRMFLG
     *
     * @return the value of HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCRMFLG
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public String getSyncrmflg() {
        return syncrmflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCRMFLG
     *
     * @param syncrmflg the value for HBEC_APPTOOLS.T_CUSTOMER_SERVICE_BRANCH.SYNCRMFLG
     *
     * @mbggenerated Mon Aug 22 09:22:04 CST 2016
     */
    public void setSyncrmflg(String syncrmflg) {
        this.syncrmflg = syncrmflg == null ? null : syncrmflg.trim();
    }

    @Override
    public String toString() {
        return "CustomerServiceBranch{" +
                "mobileno='" + mobileno + '\'' +
                ", clientId='" + clientId + '\'' +
                ", channel='" + channel + '\'' +
                ", branchno='" + branchno + '\'' +
                ", reqtime='" + reqtime + '\'' +
                ", updatetime='" + updatetime + '\'' +
                ", synclientidflg='" + synclientidflg + '\'' +
                ", syncrmflg='" + syncrmflg + '\'' +
                '}';
    }
}