package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "T_ENUM_VALUE")
public class EnumValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ENUM_VALUE.ITEM_NAME
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ENUM_VALUE.IS_SYSTEM
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    private Long isSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ENUM_VALUE.ORDERLINE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    private Long orderline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ENUM_VALUE.ITEM_CODE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ENUM_VALUE.ENUM_TYPE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    @Id
    private String enumType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ENUM_VALUE.ITEM_VALUE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    @Id
    private String itemValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_ENUM_VALUE.SITENO
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    @Id
    private String siteno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ENUM_VALUE.ITEM_NAME
     *
     * @return the value of OSOADATA.T_ENUM_VALUE.ITEM_NAME
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ENUM_VALUE.ITEM_NAME
     *
     * @param itemName the value for OSOADATA.T_ENUM_VALUE.ITEM_NAME
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ENUM_VALUE.IS_SYSTEM
     *
     * @return the value of OSOADATA.T_ENUM_VALUE.IS_SYSTEM
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public Long getIsSystem() {
        return isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ENUM_VALUE.IS_SYSTEM
     *
     * @param isSystem the value for OSOADATA.T_ENUM_VALUE.IS_SYSTEM
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public void setIsSystem(Long isSystem) {
        this.isSystem = isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ENUM_VALUE.ORDERLINE
     *
     * @return the value of OSOADATA.T_ENUM_VALUE.ORDERLINE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public Long getOrderline() {
        return orderline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ENUM_VALUE.ORDERLINE
     *
     * @param orderline the value for OSOADATA.T_ENUM_VALUE.ORDERLINE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public void setOrderline(Long orderline) {
        this.orderline = orderline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ENUM_VALUE.ITEM_CODE
     *
     * @return the value of OSOADATA.T_ENUM_VALUE.ITEM_CODE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ENUM_VALUE.ITEM_CODE
     *
     * @param itemCode the value for OSOADATA.T_ENUM_VALUE.ITEM_CODE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ENUM_VALUE.ENUM_TYPE
     *
     * @return the value of OSOADATA.T_ENUM_VALUE.ENUM_TYPE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public String getEnumType() {
        return enumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ENUM_VALUE.ENUM_TYPE
     *
     * @param enumType the value for OSOADATA.T_ENUM_VALUE.ENUM_TYPE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public void setEnumType(String enumType) {
        this.enumType = enumType == null ? null : enumType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ENUM_VALUE.ITEM_VALUE
     *
     * @return the value of OSOADATA.T_ENUM_VALUE.ITEM_VALUE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public String getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ENUM_VALUE.ITEM_VALUE
     *
     * @param itemValue the value for OSOADATA.T_ENUM_VALUE.ITEM_VALUE
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue == null ? null : itemValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_ENUM_VALUE.SITENO
     *
     * @return the value of OSOADATA.T_ENUM_VALUE.SITENO
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public String getSiteno() {
        return siteno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_ENUM_VALUE.SITENO
     *
     * @param siteno the value for OSOADATA.T_ENUM_VALUE.SITENO
     *
     * @mbggenerated Wed Aug 10 10:47:22 CST 2016
     */
    public void setSiteno(String siteno) {
        this.siteno = siteno == null ? null : siteno.trim();
    }

    @Override
    public String toString() {
        return "EnumValue{" +
                "itemName='" + itemName + '\'' +
                ", isSystem=" + isSystem +
                ", orderline=" + orderline +
                ", itemCode='" + itemCode + '\'' +
                ", enumType='" + enumType + '\'' +
                ", itemValue='" + itemValue + '\'' +
                ", siteno='" + siteno + '\'' +
                '}';
    }
}