package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@Table(name = "T_KH_TASK")
public class KhTask {

	public static final String stauts_0 = "0";//0:未处理
	public static final String stauts_1 = "1";//1:处理中
	public static final String stauts_2 = "2";//2:处理完成
	public static final String stauts_3 = "3";//3:处理失败
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column OSOADATA.T_KH_TASK.TASK_ID
	 *
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	@Id
	private Long taskId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column OSOADATA.T_KH_TASK.USER_ID
	 *
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column OSOADATA.T_KH_TASK.CREATE_DATE
	 *
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column OSOADATA.T_KH_TASK.MODIFY_DATE
	 *
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	private Date modifyDate;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column OSOADATA.T_KH_TASK.STATUS
	 *
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column OSOADATA.T_KH_TASK.TASK_NAME
	 *
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	private String taskName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column OSOADATA.T_KH_TASK.TASK_DESC
	 *
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	private String taskDesc;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column OSOADATA.T_KH_TASK.IS_LOOP
	 *
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	private String isLoop;

	@Transient
	private String custname;

	@Transient
	private String userid;

	public String getCustname() {
		return custname;
	}

	public void setCustname(String custname) {
		this.custname = custname;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column OSOADATA.T_KH_TASK.TASK_ID
	 *
	 * @return the value of OSOADATA.T_KH_TASK.TASK_ID
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public Long getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column OSOADATA.T_KH_TASK.TASK_ID
	 *
	 * @param taskId the value for OSOADATA.T_KH_TASK.TASK_ID
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column OSOADATA.T_KH_TASK.USER_ID
	 *
	 * @return the value of OSOADATA.T_KH_TASK.USER_ID
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column OSOADATA.T_KH_TASK.USER_ID
	 *
	 * @param userId the value for OSOADATA.T_KH_TASK.USER_ID
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column OSOADATA.T_KH_TASK.CREATE_DATE
	 *
	 * @return the value of OSOADATA.T_KH_TASK.CREATE_DATE
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column OSOADATA.T_KH_TASK.CREATE_DATE
	 *
	 * @param createDate the value for OSOADATA.T_KH_TASK.CREATE_DATE
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column OSOADATA.T_KH_TASK.MODIFY_DATE
	 *
	 * @return the value of OSOADATA.T_KH_TASK.MODIFY_DATE
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public Date getModifyDate() {
		return modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column OSOADATA.T_KH_TASK.MODIFY_DATE
	 *
	 * @param modifyDate the value for OSOADATA.T_KH_TASK.MODIFY_DATE
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column OSOADATA.T_KH_TASK.STATUS
	 *
	 * @return the value of OSOADATA.T_KH_TASK.STATUS
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column OSOADATA.T_KH_TASK.STATUS
	 *
	 * @param status the value for OSOADATA.T_KH_TASK.STATUS
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column OSOADATA.T_KH_TASK.TASK_NAME
	 *
	 * @return the value of OSOADATA.T_KH_TASK.TASK_NAME
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public String getTaskName() {
		return taskName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column OSOADATA.T_KH_TASK.TASK_NAME
	 *
	 * @param taskName the value for OSOADATA.T_KH_TASK.TASK_NAME
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName == null ? null : taskName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column OSOADATA.T_KH_TASK.TASK_DESC
	 *
	 * @return the value of OSOADATA.T_KH_TASK.TASK_DESC
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public String getTaskDesc() {
		return taskDesc;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column OSOADATA.T_KH_TASK.TASK_DESC
	 *
	 * @param taskDesc the value for OSOADATA.T_KH_TASK.TASK_DESC
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc == null ? null : taskDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column OSOADATA.T_KH_TASK.IS_LOOP
	 *
	 * @return the value of OSOADATA.T_KH_TASK.IS_LOOP
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public String getIsLoop() {
		return isLoop;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column OSOADATA.T_KH_TASK.IS_LOOP
	 *
	 * @param isLoop the value for OSOADATA.T_KH_TASK.IS_LOOP
	 * @mbggenerated Wed Aug 17 16:40:41 CST 2016
	 */
	public void setIsLoop(String isLoop) {
		this.isLoop = isLoop == null ? null : isLoop.trim();
	}

	@Override
	public String toString() {
		return "KhTask{" +
				"taskId=" + taskId +
				", userId=" + userId +
				", createDate=" + createDate +
				", modifyDate=" + modifyDate +
				", status='" + status + '\'' +
				", taskName='" + taskName + '\'' +
				", taskDesc='" + taskDesc + '\'' +
				", isLoop='" + isLoop + '\'' +
				", custname='" + custname + '\'' +
				", userid='" + userid + '\'' +
				'}';
	}
}