package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "T_OFFICE_HOLIDAYS")
public class OfficeHolidays {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_OFFICE_HOLIDAYS.CURRENTDAY
     *
     * @mbggenerated Mon Aug 22 13:46:19 CST 2016
     */
    @Id
    private String currentday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_OFFICE_HOLIDAYS.OFFICEFLG
     *
     * @mbggenerated Mon Aug 22 13:46:19 CST 2016
     */
    private String officeflg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_OFFICE_HOLIDAYS.CURRENTDAY
     *
     * @return the value of OSOADATA.T_OFFICE_HOLIDAYS.CURRENTDAY
     *
     * @mbggenerated Mon Aug 22 13:46:19 CST 2016
     */
    public String getCurrentday() {
        return currentday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_OFFICE_HOLIDAYS.CURRENTDAY
     *
     * @param currentday the value for OSOADATA.T_OFFICE_HOLIDAYS.CURRENTDAY
     *
     * @mbggenerated Mon Aug 22 13:46:19 CST 2016
     */
    public void setCurrentday(String currentday) {
        this.currentday = currentday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_OFFICE_HOLIDAYS.OFFICEFLG
     *
     * @return the value of OSOADATA.T_OFFICE_HOLIDAYS.OFFICEFLG
     *
     * @mbggenerated Mon Aug 22 13:46:19 CST 2016
     */
    public String getOfficeflg() {
        return officeflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_OFFICE_HOLIDAYS.OFFICEFLG
     *
     * @param officeflg the value for OSOADATA.T_OFFICE_HOLIDAYS.OFFICEFLG
     *
     * @mbggenerated Mon Aug 22 13:46:19 CST 2016
     */
    public void setOfficeflg(String officeflg) {
        this.officeflg = officeflg;
    }

    @Override
    public String toString() {
        return "OfficeHolidays{" +
                "currentday='" + currentday + '\'' +
                ", officeflg='" + officeflg + '\'' +
                '}';
    }
}