package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "T_Promote_Customer")
public class PromoteCustomer {

    public static final String isOk_0 = "0";
    public static final String isOk_1 = "1";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ID
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CUST_PHONE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private Long custPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REFEREESID
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String refereesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQDATE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String reqdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQTIME
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String reqtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.STEP
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISSYNCRM
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String issyncrm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISOK
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String isok;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISEFFECTIVE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String iseffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.UPDATETIME
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISDELETE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CLIENT_ID
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CHANNEL
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    private String channel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ID
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ID
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ID
     *
     * @param id the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ID
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CUST_PHONE
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CUST_PHONE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public Long getCustPhone() {
        return custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CUST_PHONE
     *
     * @param custPhone the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CUST_PHONE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setCustPhone(Long custPhone) {
        this.custPhone = custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REFEREESID
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REFEREESID
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getRefereesid() {
        return refereesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REFEREESID
     *
     * @param refereesid the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REFEREESID
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setRefereesid(String refereesid) {
        this.refereesid = refereesid == null ? null : refereesid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQDATE
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQDATE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getReqdate() {
        return reqdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQDATE
     *
     * @param reqdate the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQDATE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setReqdate(String reqdate) {
        this.reqdate = reqdate == null ? null : reqdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQTIME
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQTIME
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getReqtime() {
        return reqtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQTIME
     *
     * @param reqtime the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.REQTIME
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setReqtime(String reqtime) {
        this.reqtime = reqtime == null ? null : reqtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.STEP
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.STEP
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.STEP
     *
     * @param step the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.STEP
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setStep(String step) {
        this.step = step == null ? null : step.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISSYNCRM
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISSYNCRM
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getIssyncrm() {
        return issyncrm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISSYNCRM
     *
     * @param issyncrm the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISSYNCRM
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setIssyncrm(String issyncrm) {
        this.issyncrm = issyncrm == null ? null : issyncrm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISOK
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISOK
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getIsok() {
        return isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISOK
     *
     * @param isok the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISOK
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setIsok(String isok) {
        this.isok = isok == null ? null : isok.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISEFFECTIVE
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISEFFECTIVE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getIseffective() {
        return iseffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISEFFECTIVE
     *
     * @param iseffective the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISEFFECTIVE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setIseffective(String iseffective) {
        this.iseffective = iseffective == null ? null : iseffective.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.UPDATETIME
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.UPDATETIME
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.UPDATETIME
     *
     * @param updatetime the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.UPDATETIME
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISDELETE
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISDELETE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISDELETE
     *
     * @param isdelete the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.ISDELETE
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CLIENT_ID
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CLIENT_ID
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CLIENT_ID
     *
     * @param clientId the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CLIENT_ID
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CHANNEL
     *
     * @return the value of HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CHANNEL
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CHANNEL
     *
     * @param channel the value for HBEC_APPTOOLS.T_PROMOTE_CUSTOMER.CHANNEL
     *
     * @mbggenerated Mon Aug 22 09:07:19 CST 2016
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    @Override
    public String toString() {
        return "PromoteCustomer{" +
                "id='" + id + '\'' +
                ", custPhone=" + custPhone +
                ", refereesid='" + refereesid + '\'' +
                ", reqdate='" + reqdate + '\'' +
                ", reqtime='" + reqtime + '\'' +
                ", step='" + step + '\'' +
                ", issyncrm='" + issyncrm + '\'' +
                ", isok='" + isok + '\'' +
                ", iseffective='" + iseffective + '\'' +
                ", updatetime='" + updatetime + '\'' +
                ", isdelete='" + isdelete + '\'' +
                ", clientId='" + clientId + '\'' +
                ", channel='" + channel + '\'' +
                '}';
    }
}