package com.app.sjkh.pojo.local;

import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "T_TOUKERID_CLIENTID_RELATION")
public class ToukerIdClientIdRelation{

    /** 同步成功标志 */
    public static final String SyncYes = "1";
    /** 未同步标志 */
    public static final String SyncNo = "0";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.ID
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    @Id
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.CLIENT_ID
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.CREATETIME
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.UPDATETIME
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.SOURCE
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.MEMO
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.SYNCH_FLAG
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    private String synchFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.MOBILENO
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    private String mobileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.TOUKER_ID
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    private String toukerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.ID
     *
     * @return the value of OSOADATA.T_TOUKERID_CLIENTID_RELATION.ID
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.ID
     *
     * @param id the value for OSOADATA.T_TOUKERID_CLIENTID_RELATION.ID
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.CLIENT_ID
     *
     * @return the value of OSOADATA.T_TOUKERID_CLIENTID_RELATION.CLIENT_ID
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.CLIENT_ID
     *
     * @param clientId the value for OSOADATA.T_TOUKERID_CLIENTID_RELATION.CLIENT_ID
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.CREATETIME
     *
     * @return the value of OSOADATA.T_TOUKERID_CLIENTID_RELATION.CREATETIME
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.CREATETIME
     *
     * @param createtime the value for OSOADATA.T_TOUKERID_CLIENTID_RELATION.CREATETIME
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.UPDATETIME
     *
     * @return the value of OSOADATA.T_TOUKERID_CLIENTID_RELATION.UPDATETIME
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.UPDATETIME
     *
     * @param updatetime the value for OSOADATA.T_TOUKERID_CLIENTID_RELATION.UPDATETIME
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.SOURCE
     *
     * @return the value of OSOADATA.T_TOUKERID_CLIENTID_RELATION.SOURCE
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.SOURCE
     *
     * @param source the value for OSOADATA.T_TOUKERID_CLIENTID_RELATION.SOURCE
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.MEMO
     *
     * @return the value of OSOADATA.T_TOUKERID_CLIENTID_RELATION.MEMO
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.MEMO
     *
     * @param memo the value for OSOADATA.T_TOUKERID_CLIENTID_RELATION.MEMO
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.SYNCH_FLAG
     *
     * @return the value of OSOADATA.T_TOUKERID_CLIENTID_RELATION.SYNCH_FLAG
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public String getSynchFlag() {
        return synchFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.SYNCH_FLAG
     *
     * @param synchFlag the value for OSOADATA.T_TOUKERID_CLIENTID_RELATION.SYNCH_FLAG
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public void setSynchFlag(String synchFlag) {
        this.synchFlag = synchFlag == null ? null : synchFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.MOBILENO
     *
     * @return the value of OSOADATA.T_TOUKERID_CLIENTID_RELATION.MOBILENO
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public String getMobileno() {
        return mobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.MOBILENO
     *
     * @param mobileno the value for OSOADATA.T_TOUKERID_CLIENTID_RELATION.MOBILENO
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno == null ? null : mobileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.TOUKER_ID
     *
     * @return the value of OSOADATA.T_TOUKERID_CLIENTID_RELATION.TOUKER_ID
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public String getToukerId() {
        return toukerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OSOADATA.T_TOUKERID_CLIENTID_RELATION.TOUKER_ID
     *
     * @param toukerId the value for OSOADATA.T_TOUKERID_CLIENTID_RELATION.TOUKER_ID
     *
     * @mbggenerated Fri Aug 12 09:38:26 CST 2016
     */
    public void setToukerId(String toukerId) {
        this.toukerId = toukerId == null ? null : toukerId.trim();
    }

    @Override
    public String toString() {
        return "ToukerIdClientIdRelation{" +
                "id=" + id +
                ", clientId='" + clientId + '\'' +
                ", createtime='" + createtime + '\'' +
                ", updatetime='" + updatetime + '\'' +
                ", source='" + source + '\'' +
                ", memo='" + memo + '\'' +
                ", synchFlag='" + synchFlag + '\'' +
                ", mobileno='" + mobileno + '\'' +
                ", toukerId='" + toukerId + '\'' +
                '}';
    }
}